# Generated by Django 2.1.7 on 2019-02-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Song title')),
                ('artist', models.CharField(max_length=200, verbose_name='Artist name')),
                ('album', models.CharField(max_length=200, verbose_name='Album name')),
                ('release_date', models.DateField(verbose_name='Date of release')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.CharField(max_length=75, verbose_name='email')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.User'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user_id', 'song_id')},
        ),
    ]
