# Generated by Django 2.1.7 on 2019-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=60, verbose_name='Password'),
        ),
    ]
