# Generated by Django 2.1.7 on 2019-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='time_range',
            field=models.CharField(default='Short term', max_length=10, verbose_name='Time range'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='acousticness',
            field=models.FloatField(default=1, max_length=10, verbose_name='Acousticness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='danceability',
            field=models.FloatField(default=1, max_length=10, verbose_name='Danceability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(default=1, max_length=10, verbose_name='Energy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='instrumentalness',
            field=models.FloatField(default=1, max_length=10, verbose_name='Instrumentalness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.FloatField(default=1, max_length=10, verbose_name='Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='liveness',
            field=models.FloatField(default=1, max_length=10, verbose_name='Liveness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='loudness',
            field=models.FloatField(default=1, max_length=10, verbose_name='Loudness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='mode',
            field=models.FloatField(default=1, max_length=10, verbose_name='Mode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='speechiness',
            field=models.FloatField(default=1, max_length=10, verbose_name='Speechiness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='tempo',
            field=models.FloatField(default=1, max_length=10, verbose_name='Tempo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.FloatField(default=1, max_length=10, verbose_name='Valence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.IntegerField(verbose_name='Year of release'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Song ID'),
        ),
    ]
