# Generated by Django 2.1.7 on 2019-02-26 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0002_auto_20190226_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist',
            new_name='UserTopTracks',
        ),
    ]
