# Generated by Django 2.1.7 on 2019-02-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20190213_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=75, unique=True, verbose_name='email'),
        ),
    ]
