# Generated by Django 2.1.7 on 2019-02-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20190226_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoptracks',
            name='time_range',
            field=models.CharField(max_length=11, verbose_name='Time range'),
        ),
    ]
