# Generated by Django 2.1.7 on 2019-02-28 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0004_auto_20190228_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertoptracks',
            unique_together={('user_id', 'song_id', 'time_range')},
        ),
    ]
